import type { Post, PostComment, PostLike } from "@/features/home/types";

const mojtamaAvatar = require("@/features/home/constants/mojtama-avatar.png");
const dummyFeedImage = require("@/features/home/constants/dummy-feed.jpg");
const dummyUserAvatar = require("@/features/home/constants/dummy-avatar.jpg");

export const DUMMY_POSTS: Post[] = [
  {
    id: "1",
    type: "announcements",
    authorName: "Mojtama - مجتمع",
    authorAvatar: mojtamaAvatar,
    timestamp: "32m",
    title: "New Gym equipment installation",
    body: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance assistance The elevator is currently out of service....",
    likesCount: 1295,
    commentsCount: 638,
    viewsCount: 405,
    category: "General",
    postedAt: "Today , 9:09 PM",
    visibility: "All Members",
  },
  {
    id: "2",
    type: "news",
    authorName: "Mojtama - مجتمع",
    authorAvatar: mojtamaAvatar,
    timestamp: "32m",
    image: dummyFeedImage,
    title: "New Gym equipment installation",
    body: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance assistance The elevator is currently out of service....",
    likesCount: 1295,
    commentsCount: 638,
    viewsCount: 405,
    category: "General",
    postedAt: "Today , 9:09 PM",
    visibility: "All Members",
  },
  {
    id: "3",
    type: "meeting",
    title: "Community Safety",
    status: "Upcoming",
    body: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance assistance",
    leadBy: {
      name: "Jade Smith",
      avatar: dummyUserAvatar,
    },
    meetingType: "In-Person meeting",
    location: "Community hall",
    date: "30 December, 2024",
    time: "8:00 AM — 9:00 AM",
    likesCount: 1295,
    commentsCount: 638,
    viewsCount: 405,
    category: "General",
    postedAt: "Today , 9:09 PM",
    visibility: "All Members",
  },
  {
    id: "4",
    type: "poll",
    authorName: "Mojtama - مجتمع",
    authorAvatar: mojtamaAvatar,
    timestamp: "32m",
    title: "Adding new service",
    body: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance ...",
    options: [
      { id: "gym", label: "Gym", votes: 641 },
      { id: "cafe", label: "Cafe", votes: 452 },
      { id: "library", label: "Library", votes: 123 },
    ],
    likesCount: 1295,
    commentsCount: 638,
    viewsCount: 405,
    category: "General",
    postedAt: "Today , 9:09 PM",
    visibility: "All Members",
  },
];

export const DUMMY_LIKES: PostLike[] = [
  {
    id: "1",
    name: "Jade Smith",
    unit: "2A/B",
    time: "8:30PM",
    avatar: dummyUserAvatar,
  },
  { id: "2", name: "Priya Sharma", unit: "2A/B", time: "6:30PM" },
  {
    id: "3",
    name: "Omar Ali",
    unit: "2A/B",
    time: "3:30PM",
    avatar: dummyUserAvatar,
  },
  {
    id: "4",
    name: "Ahmed Fawzy",
    unit: "2A/B",
    time: "12:30PM",
    avatar: dummyUserAvatar,
  },
  { id: "5", name: "Manar Khaled", unit: "2A/B", time: "4:30AM" },
  {
    id: "6",
    name: "Jade Smith",
    unit: "2A/B",
    time: "Yesterday - 11:30PM",
    avatar: dummyUserAvatar,
  },
  { id: "7", name: "Jade Smith", unit: "2A/B", time: "Yesterday - 6:30PM" },
];

export const DUMMY_COMMENTS: PostComment[] = [
  {
    id: "1",
    authorName: "Jade Smith",
    time: "4:30PM",
    text: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance assistance.",
    likesCount: 1295,
    avatar: dummyUserAvatar,
    replies: [
      {
        id: "1-1",
        authorName: "Jade Smith",
        time: "4:30PM",
        text: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance assistan cestairs or contact maintenance assistance...",
        likesCount: 1295,
        avatar: dummyUserAvatar,
      },
      {
        id: "1-2",
        authorName: "Jade Smith",
        time: "4:30PM",
        text: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance assistan cestairs or contact maintenance assistance...",
        likesCount: 1295,
        avatar: dummyUserAvatar,
      },
    ],
  },
  {
    id: "2",
    authorName: "Jade Smith",
    time: "4:30PM",
    text: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance assistance.",
    likesCount: 1295,
    avatar: dummyUserAvatar,
  },
];
