import type { Member, Post, PostComment, PostLike } from "@/features/home/types";

const mojtamaAvatar = require("@/features/home/constants/mojtama-avatar.png");
const dummyFeedImage = require("@/features/home/constants/dummy-feed.jpg");
const dummyUserAvatar = require("@/features/home/constants/dummy-avatar.jpg");

export const DUMMY_POSTS: Post[] = [
  {
    id: "1",
    type: "announcements",
    authorName: "Mojtama - مجتمع",
    authorAvatar: mojtamaAvatar,
    timestamp: "32m",
    title: "New Gym equipment installation",
    body: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance assistance The elevator is currently out of service....",
    likesCount: 1295,
    commentsCount: 638,
    viewsCount: 405,
    category: "General",
    postedAt: "Today , 9:09 PM",
    visibility: "All Members",
  },
  {
    id: "2",
    type: "news",
    authorName: "Mojtama - مجتمع",
    authorAvatar: mojtamaAvatar,
    timestamp: "32m",
    image: dummyFeedImage,
    title: "New Gym equipment installation",
    body: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance assistance The elevator is currently out of service....",
    likesCount: 1295,
    commentsCount: 638,
    viewsCount: 405,
    category: "General",
    postedAt: "Today , 9:09 PM",
    visibility: "All Members",
  },
  {
    id: "3",
    type: "meeting",
    title: "Resident Meeting Proposal",
    status: "Upcoming",
    body: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance assistance The elevator is currently out of service....",
    agenda: "Quarterly Community Updates",
    leadBy: {
      name: "Dr. Samer Mohamed",
      avatar: dummyUserAvatar,
    },
    createdBy: "Mohamed Fawazy",
    meetingType: "Virtual meeting",
    location: "Virtual meeting",
    meetingLink: "braavos.meet.google.com/iou-jytx-yvj",
    date: "May 30, 2026",
    time: "01:00 PM — 03:00 PM",
    duration: "2h",
    isPublic: true,
    likesCount: 1295,
    commentsCount: 638,
    viewsCount: 405,
    category: "General",
    postedAt: "Today , 9:09 PM",
    visibility: "All Members",
    attendees: [
      {
        id: "a1",
        name: "Ali Abdelhamid",
        unit: "5A/B",
        avatar: dummyUserAvatar,
        status: "attending",
        group: "residents",
      },
      {
        id: "a2",
        name: "Ali Abdelhamid",
        unit: "5A/B",
        avatar: dummyUserAvatar,
        status: "declined",
        group: "residents",
      },
      {
        id: "a3",
        name: "Ali Abdelhamid",
        unit: "5A/B",
        avatar: dummyUserAvatar,
        status: "awaiting",
        group: "residents",
      },
      {
        id: "a4",
        name: "Priya Sharma",
        unit: "2A/B",
        status: "attending",
        group: "team",
      },
      {
        id: "a5",
        name: "Jade Smith",
        unit: "3C/D",
        avatar: dummyUserAvatar,
        status: "awaiting",
        group: "team",
      },
    ],
    agendaItems: [
      {
        id: "ag1",
        title: "Welcome & Intro",
        timeRange: "01:00 PM - 01:15 PM",
      },
      {
        id: "ag2",
        title: "Community Updates",
        timeRange: "01:15 PM - 01:45 PM",
      },
      {
        id: "ag3",
        title: "Upcoming Projects",
        timeRange: "01:45 PM - 02:30 PM",
      },
      {
        id: "ag4",
        title: "Open Discussion",
        timeRange: "02:30 PM - 03:00 PM",
      },
    ],
  },
  {
    id: "4",
    type: "poll",
    authorName: "Mojtama - مجتمع",
    authorAvatar: mojtamaAvatar,
    timestamp: "32m",
    title: "Adding new service",
    body: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance ...",
    options: [
      { id: "gym", label: "Gym", votes: 641 },
      { id: "cafe", label: "Cafe", votes: 452 },
      { id: "library", label: "Library", votes: 123 },
      { id: "pool", label: "Swimming Pool", votes: 98 },
      { id: "spa", label: "Spa", votes: 76 },
      { id: "coworking", label: "Co-working Space", votes: 54 },
    ],
    likesCount: 1295,
    commentsCount: 638,
    viewsCount: 405,
    category: "General",
    postedAt: "Today , 9:09 PM",
    visibility: "All Members",
  },
];

export const DUMMY_LIKES: PostLike[] = [
  {
    id: "1",
    name: "Jade Smith",
    unit: "2A/B",
    time: "8:30PM",
    avatar: dummyUserAvatar,
  },
  { id: "2", name: "Priya Sharma", unit: "2A/B", time: "6:30PM" },
  {
    id: "3",
    name: "Omar Ali",
    unit: "2A/B",
    time: "3:30PM",
    avatar: dummyUserAvatar,
  },
  {
    id: "4",
    name: "Ahmed Fawzy",
    unit: "2A/B",
    time: "12:30PM",
    avatar: dummyUserAvatar,
  },
  { id: "5", name: "Manar Khaled", unit: "2A/B", time: "4:30AM" },
  {
    id: "6",
    name: "Jade Smith",
    unit: "2A/B",
    time: "Yesterday - 11:30PM",
    avatar: dummyUserAvatar,
  },
  { id: "7", name: "Jade Smith", unit: "2A/B", time: "Yesterday - 6:30PM" },
];

export const DUMMY_MEMBERS: Member[] = [
  {
    id: "1",
    name: "Priya Sharma",
    role: "Finance officer",
    email: "priya.sharma@gmail.com",
  },
  {
    id: "2",
    name: "Jade Smith",
    role: "Community manager",
    email: "jadesmith@gmail.com",
    avatar: dummyUserAvatar,
  },
  {
    id: "3",
    name: "Omar Ali",
    role: "Maintenance lead",
    email: "omar.ali@gmail.com",
    avatar: dummyUserAvatar,
  },
  {
    id: "4",
    name: "Manar Khaled",
    role: "Events coordinator",
    email: "manar.khaled@gmail.com",
  },
  {
    id: "5",
    name: "Ahmed Fawzy",
    role: "Security officer",
    email: "ahmed.fawzy@gmail.com",
    avatar: dummyUserAvatar,
  },
  {
    id: "6",
    name: "Jana Saeed",
    role: "Resident representative",
    email: "jana.saeed@gmail.com",
  },
];

export const DUMMY_COMMENTS: PostComment[] = [
  {
    id: "1",
    authorName: "Jade Smith",
    time: "4:30PM",
    text: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance assistance.",
    likesCount: 1295,
    avatar: dummyUserAvatar,
    replies: [
      {
        id: "1-1",
        authorName: "Jade Smith",
        time: "4:30PM",
        text: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance assistan cestairs or contact maintenance assistance...",
        likesCount: 1295,
        avatar: dummyUserAvatar,
      },
      {
        id: "1-2",
        authorName: "Jade Smith",
        time: "4:30PM",
        text: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance assistan cestairs or contact maintenance assistance...",
        likesCount: 1295,
        avatar: dummyUserAvatar,
      },
    ],
  },
  {
    id: "2",
    authorName: "Jade Smith",
    time: "4:30PM",
    text: "The elevator is currently out of service due to a malfunction. Please use the stairs or contact maintenance assistance.",
    likesCount: 1295,
    avatar: dummyUserAvatar,
  },
];
